### ISSUE TITLE
AttributeError: 'JwstAperture' object has no attribute 'set_attitude_matrix'

### ISSUE THREAD

**Issue by cnaw** [spacetelescope/jwst_visit_viewer#1]
I set conda activate astroconda and followed the installation instructions for jwst_visit_viewer, and sky_transforms.  Not being an expert git user I did this:

(astroconda) [cnaw@tangara python]$ git pull https://github.com/spacetelescope/pysiaf/pull/177
fatal: Not a git repository (or any of the parent directories): .git

Assuming this is not  major issue I go into the examples directory and this happens:

(astroconda) [cnaw@tangara examples]$ visitviewer V00747016001.vst
Traceback (most recent call last):
  File "/home/cnaw/anaconda3/envs/astroconda/bin/visitviewer", line 8, in <module>
    sys.exit(main())
  File "/home/cnaw/anaconda3/envs/astroconda/lib/python3.6/site-packages/visitviewer/__init__.py", line 32, in main
    view(args.filename, save=True)
  File "/home/cnaw/anaconda3/envs/astroconda/lib/python3.6/site-packages/visitviewer/__init__.py", line 23, in view
    visitplotter.multi_plot(visit, save=save, verbose=verbose, **kwargs)
  File "/home/cnaw/anaconda3/envs/astroconda/lib/python3.6/site-packages/visitviewer/visitplotter.py", line 543, in multi_plot
    plot_visit_fov(visit, subplotspec=gs_outer[0])
  File "/home/cnaw/anaconda3/envs/astroconda/lib/python3.6/site-packages/visitviewer/visitplotter.py", line 96, in plot_visit_fov
    fgs_aperture.set_attitude_matrix(attmat)
AttributeError: 'JwstAperture' object has no attribute 'set_attitude_matrix'

I get the same error when running the notebook.

**Comment by mperrin** [comment]
HI @cnaw, that error indicated that you have the regular version of `pysiaf` without that pull request. That function is one of the things I added in the sky transforms branch.  

If you activate astroconda and then run this command, does it look like it successfully downloads and installs anything? 
```
pip install git+https://github.com/mperrin/pysiaf.git@sky_transforms
```

**Comment by cnaw** [comment]
I get this:
... (several messages about satisfied requirements)

  Building wheel for pysiaf (setup.py) ... done
  Created wheel for pysiaf: filename=pysiaf-0.0.1-py2.py3-none-any.whl size=36110833 sha256=669be7d5841eb311e55473894043aa73fb245c6c090c8e761ad24f8d59440c87
  Stored in directory: /tmp/pip-ephem-wheel-cache-tntvj_1r/wheels/f0/58/d3/d837750238904e0466d06917b54310f3ac69a6d7dc821e76b9
Successfully built pysiaf
Installing collected packages: pysiaf
  Attempting uninstall: pysiaf
    Found existing installation: pysiaf 0.11.0
    Uninstalling pysiaf-0.11.0:
      Successfully uninstalled pysiaf-0.11.0
ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.

We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.

webbpsf 0.9.0 requires pysiaf>=0.6.0, but you'll have pysiaf 0.0.1 which is incompatible.
Successfully installed pysiaf-0.0.1

**Comment by mperrin** [comment]
hmm, that looks like it's installing a version from that branch, it seems. (I see the version number gets confused because the version tag is only on the master branch) So I am not sure why it isn't getting the updated version. 

I have been waiting for the maintainer of pysiaf to go ahead and merge those changes into that, but that's gotten delayed by some unrelated GitHub issues... 

I can walk you through the git steps to check out and install pysiaf directly if you want? Or we can wait until after this PR gets merged, when hopefully things will be more straightforward?

**Comment by cnaw** [comment]
On my side I would wait until PR  issue is resolved. I think it will the path of least resistance. I guess this issue can be closed.

**Comment by mfixstsci** [comment]
@cnaw I just merged the pull request in `pysiaf` that should address this issue.

**Comment by cnaw** [comment]
Fantastic ! It runs both in the notebook and as stand-alone, so Success!!
I followed the sequence of instructions and probably this is not required any more:
pip install git+https://github.com/mperrin/pysiaf.git@sky_transforms

as I get an error, but the script works anyway:
Collecting git+https://github.com/mperrin/pysiaf.git@sky_transforms
  Cloning https://github.com/mperrin/pysiaf.git (to revision sky_transforms) to /tmp/pip-req-build-7ju082sw
  WARNING: Did not find branch or tag 'sky_transforms', assuming revision or ref.
ERROR: Command errored out with exit status 1: git checkout -q sky_transforms Check the logs for full command output.
 I assume the issue can be closed. Thanks a lot!
